defaultSemverRangePrefix: ''

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.8.1/index.cjs'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.5.cjs
