version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:lts
commands:
  restore-deps:
    steps:
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
  install-deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            yarn install
  save-deps:
    steps:
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Show environment information
          command: |
            echo "node: $(node -v)"
            echo "yarn: $(yarn -v)"
      - restore-deps
      - install-deps
      - save-deps
workflows:
  build:
    jobs:
      - build
