const config = {
  $schema: './node_modules/oxlint/configuration_schema.json',
  plugins: ['eslint', 'import', 'jsx-a11y', 'oxc', 'promise', 'react', 'react-perf', 'typescript', 'unicorn'],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  env: {
    builtin: true,
    es2026: true,
    browser: true,
    node: true,
    serviceworker: true,
  },
  ignorePatterns: [
    '**/.agents/**',
    '**/.claude/**',
    '**/.devcontainer/**',
    '**/.idea/AugmentWebviewStateStore.xml',
    '**/.idea/copilot.*/**',
    '**/.idea/copilot/**',
    '**/.playwright-cli/**',
    '**/.serena/**',
    '**/.tmp/**',
    '**/.venv/**',
    '**/.yarn/**',
    '**/3rd-party/**',
    '**/@types/**',
    '**/@willbooster/**',
    '**/__generated__/**',
    '**/android/**',
    '**/bin/**',
    '**/build/**',
    '**/coverage/**',
    '**/dist/**',
    '**/ios/**',
    '**/no-format/**',
    '**/node_modules/**',
    '**/temp/**',
    '**/tmp/**',
    '**/test-fixtures/**',
    '**/test-results/**',
    '**/test/fixtures/**',
    '**/.aider*',
    '**/.env.production',
    '**/.pnp.js',
    '**/*/mount/*.hash',
    '**/*.d.ts',
    '**/*.min.*js',
  ],
  rules: {
    // Loose equality can be intentional for nullish checks and legacy APIs, so keep it visible without blocking.
    eqeqeq: 'warn',
    'no-console': 'off',
    // Unused variables are often temporary during development; type-aware unused-import checks catch the stricter cleanup cases.
    'no-unused-vars': [
      'warn',
      {
        ignoreRestSiblings: true,
      },
    ],
    'object-shorthand': 'error',
    'import-x/default': 'error',
    'import-x/export': 'error',
    'import-x/named': 'error',
    'import-x/namespace': 'error',
    'import-x/no-duplicates': 'error',
    // Some packages intentionally expose useful default imports alongside named exports, so do not block those imports.
    'import-x/no-named-as-default': 'warn',
    // Default namespace-style imports such as `yaml.load` can be clearer than detached named imports for module APIs.
    'import-x/no-named-as-default-member': 'warn',
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/img-redundant-alt': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-autofocus': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',
    'promise/always-return': 'error',
    'promise/catch-or-return': 'error',
    // Callback interop inside promises is common when wrapping older Node APIs, so report it without forcing rewrites.
    'promise/no-callback-in-promise': 'warn',
    'promise/no-new-statics': 'error',
    // Nested promise flows can be readable for scoped error handling, so keep this advisory.
    'promise/no-nesting': 'warn',
    // Passing promises through callback APIs happens at library boundaries and should not block builds.
    'promise/no-promise-in-callback': 'warn',
    // Returning from finally is suspicious but can be intentional in cleanup abstractions, so keep it non-blocking.
    'promise/no-return-in-finally': 'warn',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    // This rule can flag library-specific promise signatures, so keep it visible without making it fatal.
    'promise/valid-params': 'warn',
    // React Compiler and framework-specific component APIs make these prop allocation rules too noisy
    // for shared enforcement. Projects can still opt in locally when referential stability is required.
    'react-perf/jsx-no-new-array-as-prop': 'off',
    'react-perf/jsx-no-new-function-as-prop': 'off',
    'react-perf/jsx-no-new-object-as-prop': 'off',
    'react/display-name': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'error',
    'react/no-unescaped-entities': 'error',
    'react/no-unknown-property': 'error',
    'react/no-unsafe': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/require-render-return': 'error',
    // Some hooks intentionally omit non-reactive values that are not allowed to change after initialization.
    'react-hooks/exhaustive-deps': 'warn',
    'unicorn/catch-error-name': 'error',
    'unicorn/consistent-assert': 'error',
    'unicorn/consistent-date-clone': 'error',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-existence-index-check': 'error',
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/consistent-template-literal-escape': 'error',
    'unicorn/empty-brace-spaces': 'error',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/explicit-length-check': 'error',
    'unicorn/filename-case': [
      'error',
      {
        cases: {
          camelCase: true,
          pascalCase: true,
        },
      },
    ],
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-abusive-eslint-disable': 'off',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/no-array-for-each': 'error',
    'unicorn/no-array-method-this-argument': 'error',
    // Reduce can be the clearest expression for accumulators, especially when avoiding extra intermediate objects.
    'unicorn/no-array-reduce': 'warn',
    'unicorn/no-array-reverse': 'error',
    'unicorn/no-array-sort': 'error',
    'unicorn/no-await-expression-member': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-console-spaces': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-empty-file': 'error',
    'unicorn/no-hex-escape': 'error',
    'unicorn/no-immediate-mutation': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/no-magic-array-flat-depth': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    // Nested ternaries can remain readable for compact value selection and oxfmt may remove grouping parentheses.
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    // Some external APIs and generated config formats require `null` to represent explicit empty values.
    'unicorn/no-null': 'warn',
    'unicorn/no-object-as-default-parameter': 'error',
    'unicorn/no-process-exit': 'off',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-this-assignment': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-unnecessary-array-flat-depth': 'error',
    'unicorn/no-unnecessary-array-splice-count': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-unnecessary-slice-end': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unreadable-iife': 'error',
    'unicorn/no-useless-collection-argument': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-iterator-to-array': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/no-useless-undefined': [
      'error',
      {
        checkArguments: false,
      },
    ],
    'unicorn/no-zero-fractions': 'error',
    // Oxfmt may normalize numeric literal casing differently, so report style mismatches without blocking.
    'unicorn/number-literal-case': 'warn',
    'unicorn/numeric-separators-style': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-index-of': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-bigint-literals': 'error',
    'unicorn/prefer-blob-reading-methods': 'error',
    'unicorn/prefer-class-fields': 'error',
    'unicorn/prefer-classlist-toggle': 'error',
    'unicorn/prefer-code-point': 'error',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-default-parameters': 'error',
    'unicorn/prefer-dom-node-append': 'error',
    'unicorn/prefer-dom-node-dataset': 'error',
    'unicorn/prefer-dom-node-remove': 'error',
    'unicorn/prefer-dom-node-text-content': 'error',
    'unicorn/prefer-event-target': 'error',
    'unicorn/prefer-global-this': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-keyboard-event-key': 'error',
    'unicorn/prefer-logical-operator-over-ternary': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-modern-dom-apis': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-native-coercion-functions': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-prototype-methods': 'error',
    'unicorn/prefer-query-selector': 'error',
    'unicorn/prefer-reflect-apply': 'error',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-response-static-json': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-string-raw': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/prefer-ternary': 'error',
    // Top-level await affects module loading semantics and package compatibility, so treat it as guidance.
    'unicorn/prefer-top-level-await': 'warn',
    'unicorn/prefer-type-error': 'error',
    'unicorn/relative-url-style': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-module-attributes': 'error',
    'unicorn/require-module-specifiers': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/switch-case-braces': 'error',
    'unicorn/switch-case-break-position': 'error',
    'unicorn/text-encoding-identifier-case': 'error',
    'unicorn/throw-new-error': 'error',
  },
  overrides: [
    {
      files: [
        '**/app/**/{global-error,not-found}.{js,jsx,ts,tsx}',
        '**/pages/{_app,_document,_error,404,500}.{js,jsx,ts,tsx}',
      ],
      rules: {
        // These filenames are reserved by Next.js and cannot be renamed to camelCase or PascalCase.
        'unicorn/filename-case': 'off',
      },
    },
    {
      files: ['{,prisma/**/,src/**/,test/**/,scripts/**/}*.{cts,mts,ts,tsx}'],
      rules: {
        '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
        '@typescript-eslint/consistent-type-imports': 'error',
        '@typescript-eslint/explicit-function-return-type': [
          'error',
          {
            allowExpressions: true,
            allowHigherOrderFunctions: true,
          },
        ],
        '@typescript-eslint/no-explicit-any': 'error',
        '@typescript-eslint/no-misused-promises': [
          'error',
          {
            checksVoidReturn: {
              arguments: false,
              attributes: false,
            },
          },
        ],
        'no-unused-vars': [
          'error',
          {
            argsIgnorePattern: '^_',
            ignoreRestSiblings: true,
          },
        ],
        '@typescript-eslint/non-nullable-type-assertion-style': 'off',
        '@typescript-eslint/prefer-nullish-coalescing': [
          'error',
          {
            ignorePrimitives: true,
          },
        ],
        '@typescript-eslint/restrict-template-expressions': 'off',
        'no-use-before-define': 'off',
      },
    },
  ],
};

export default config;
